### ISSUE TITLE
A problem for "Time shifting for spaced repetition or date postponing"

### ISSUE THREAD

**Issue by aybeex** [mdelobelle/metadatamenu#124]
Hello:

When I use next interval to improve date, like "1 day,2 days, 1 week,2 weeks","cycle through values from a list" can't be used.
![image](https://user-images.githubusercontent.com/115936461/196043311-4430da33-b8b9-4c61-8b74-7d0c87bb446d.png)

This function is very useful to me. 
Waiting your help.

**Comment by mdelobelle** [comment]
Hi, could you show me the settings for this field?

**Comment by mdelobelle** [comment]
Oh nevermind, i can reproduce this issue. I'll keep you posted

**Comment by mdelobelle** [comment]
This is fixed in version 0.2.12
Can you check that it's ok for you now?

**Comment by aybeex** [comment]
I'm sorry. That isn't used still.
Check it again please.
It is amazing for reviewing knowledge, I think it will be a tool for my son's learning.

Thanks.

**Comment by mdelobelle** [comment]
can you take the same screenshot again please?

**Comment by aybeex** [comment]
thanks


曲正
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mdelobelle/metadatamenu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mdelobelle/metadatamenu] A problem for "Time shifting for spaced repetition or date postponing" (Issue #124)





 
can you take the same screenshot again please?

**Comment by mdelobelle** [comment]
did you paste something? I can't see any picture in your comment

**Comment by aybeex** [comment]
last time， I gave you&nbsp; a PDF&nbsp;
This time ,it is a ".md" file in attachment.




曲正
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mdelobelle/metadatamenu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mdelobelle/metadatamenu] A problem for "Time shifting for spaced repetition or date postponing" (Issue #124)





 
did you paste something? I can't see any picture in your comment

**Comment by mdelobelle** [comment]
I didn't receive the attachement,
Can you paste the content of the .md file?

**Comment by aybeex** [comment]
![](https://s1.vika.cn/space/2022/10/17/fc093560fd6945e9be316547e156da33)


![](https://s1.vika.cn/space/2022/10/17/2edfa034459b4c9a897900b4e261fd41)


![](https://s1.vika.cn/space/2022/10/17/2f9c25640c114362af873e4157dabcfc)


![](https://s1.vika.cn/space/2022/10/17/07ba18f186d742eabae46ff7e6b42533)


![](https://s1.vika.cn/space/2022/10/17/2eccb7887cce424f9292093d85bd5a44)



&nbsp;


曲正
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mdelobelle/metadatamenu] A problem for &quot;Time shifting for spaced repetition or date postponing&quot; (Issue #124)





 
I didn't receive the attachement,
 Can you paste the content of the .md file?

**Comment by mdelobelle** [comment]
ok the settings are ok.
Do you have any error in the console? (ctrl+alt+i or cmd+opt+i on mac)

**Comment by aybeex** [comment]
曲正
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mdelobelle/metadatamenu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mdelobelle/metadatamenu] A problem for "Time shifting for spaced repetition or date postponing" (Issue #124)





 
ok the settings are ok.
 Do you have any error in the console? (ctrl+alt+i or cmd+opt+i on mac)

**Comment by aybeex** [comment]
![image](https://user-images.githubusercontent.com/115936461/196149120-8e596860-77bc-4a18-bf43-9ba9312e2e85.png)

**Comment by mdelobelle** [comment]
it looks like it is an issue with the dataview api.
what is the version of dataview that you currently use?

**Comment by aybeex** [comment]
![image](https://user-images.githubusercontent.com/115936461/196150979-08abf8b3-cd4f-490a-a955-2bd20c6d872b.png)

**Comment by mdelobelle** [comment]
I've pushed a hotfix: v0.2.13.
Could you test it?

**Comment by aybeex** [comment]
It has worked.
have a problem still.
"Cycle through values from a list" cycles only 4 times. 
![image](https://user-images.githubusercontent.com/115936461/196163318-2df4cafa-ca32-4a52-b2d1-2dd80eec8825.png)

**Comment by aybeex** [comment]
OK
